version: '3.8'

name: memo-dev

services:
  app:
    container_name: memo-dev-app
    build:
      context: ../..
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://memo_user:memo_password@db:5432/memo_dev
    volumes:
      - ../../:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - memo-dev-network

  db:
    container_name: memo-dev-db
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=memo_dev
      - POSTGRES_USER=memo_user
      - POSTGRES_PASSWORD=memo_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ../../scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - memo-dev-network

volumes:
  postgres_dev_data:

networks:
  memo-dev-network:
    driver: bridge
