name: Validate PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (based on conventional commits)
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Configure scopes (optional)
          scopes: |
            ui
            api
            db
            docker
            ci
            docs
            deps
          # Require a scope
          requireScope: false
          # Disallow use of uppercase in subject
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          # GitHub base URL for enterprise
          githubBaseUrl: https://github.com
          # Only validate the PR title, not individual commits
          validateSingleCommit: false
          # Ignore merge commits
          ignoreLabels: |
            ignore-semantic-pull-request